name: build

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-20.04]
        go-version: [1.17.x]
    runs-on: ${{ matrix.platform }}
    name: Linters (Static Analysis) for Go
    env:
      GOBIN: /tmp/.bin
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Build
        run: |
         - CGO_ENABLED=1 GOOS=linux go build -a -v -i -o /tmp/vault-ethereum-${{ matrix.platform }} .
           #         - sha256sum -b /tmp/vault-ethereum-${{ matrix.platform }} > /tmp/vault-ethereum-sha256sum-${{ matrix.platform }}

      - name: generate sha256sum file
        run: sha256sum -b /tmp/vault-ethereum-${{ matrix.platform }} > /tmp/vault-ethereum-sha256sum-${{ matrix.platform }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            /tmp/vault-ethereum-${{ matrix.platform }}
            /tmp/vault-ethereum-sha256sum-${{ matrix.platform }}

            #      - name: Upload binaries to release
            #        uses: svenstaro/upload-release-action@v2
            #        with:
            #          repo_token: ${{ secrets.GITHUB_TOKEN }}
            #          file: /tmp/vault-ethereum-*
            #          asset_name: vault-ethereum-${{ matrix.platform }}
            #          tag: ${{ github.ref }}
            #          overwrite: true
            #          body: "This is my release text"
