name: release

on:
  release:
    types: [created]
#on:
#  - push
#  - pull_request

jobs:
  build:
    name: Build and release
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            goos: linux
            goarch: amd64
          - os: macos-11
            goos: darwin
            goarch: amd64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v2

        #      - name: Install Go
        #        uses: actions/setup-go@v2
        #
        #      - name: Build and generate sha256sum file
        #        env:
        #          CGO_ENABLED: 1
        #          GOOS: ${{ matrix.goos }}
        #          GOARCH: ${{ matrix.goarch }}
        #        run: |
        #          CGO_ENABLED=1 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags '-extldflags "-static"' -v -o /tmp/vault-ethereum-${{ matrix.goos }}-${{ matrix.goarch }} .
        #          sha256sum -b /tmp/vault-ethereum-${{ matrix.platform }} > /tmp/vault-ethereum-sha256sum-${{ matrix.goos }}-${{ matrix.goarch }}
        #
        #      - name: Release
        #        uses: softprops/action-gh-release@v1
        #        if: startsWith(github.ref, 'refs/tags/')
        #        with:
        #          files: |
        #            /tmp/vault-ethereum-${{ matrix.goos }}-${{ matrix.goarch }}
        #            /tmp/vault-ethereum-sha256sum-${{ matrix.goos }}-${{ matrix.goarch }}
        #
      - uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          build_flags: -v
          ldflags: -extldflags "-static"
