name: release

on:
  - push
  - pull_request

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64]
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build and generate sha256sum file
        env:
          CGO_ENABLED: 1
          GOOS: ${{ matrix.goos }}
          #          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -ldflags '-extldflags "-static"' -v -o /tmp/vault-ethereum-${{ matrix.goos }}-${{ matrix.goarch }} .
          sha256sum -b /tmp/vault-ethereum-${{ matrix.platform }} > /tmp/vault-ethereum-sha256sum-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            /tmp/vault-ethereum-${{ matrix.goos }}-${{ matrix.goarch }}
            /tmp/vault-ethereum-sha256sum-${{ matrix.goos }}-${{ matrix.goarch }}
